apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::123456789012:role/default_node_group-eks-node-group-20230815012139713800000002
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - demo:view
      rolearn: arn:aws:iam::123456789012:role/RbacDemoRole
      username: view-user
