apiVersion: apps/v1
kind: Deployment

metadata:
  name: website

spec:
  replicas: 2
  selector:
    matchLabels:
      app: website

  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: devteds/demo-bookstore-website:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1" # CPUの最大値を1コアに制限
            memory: "512Mi" # メモリの最大値を512Miに制限

